server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/staff_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
    show-sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.ehr.staffservice.controller
  paths-to-match: /api/**

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

appointment-service:
  base-url: http://localhost:8088

patient-service:
  base-url: http://localhost:8089   